"""Write the demo household's statements in each bank's format, laid out the way the parsers read them.

The PDFs are drawn with PyMuPDF at the x/y positions each parser expects (see the layout notes in
slopfi/parsers/*.py); the Monzo export is a CSV with Monzo's column headings. Every file carries a line saying
it is fictional demo data. Output is byte-for-byte deterministic: fixed metadata, no random document ids.
"""
from __future__ import annotations

import calendar
import csv
import io
from datetime import date, timedelta
from pathlib import Path

import pymupdf

from .household import ADDRESS, Account, Household, Pot, Txn

FONT, BOLD = "helv", "hebo"
PAGE_W, PAGE_H = 595, 842
DISCLAIMER = "Fictional demo statement generated by slopFi. Not a real bank document: every name and number is made up."
FIXED_DATE = "D:20260101000000Z"


def _money(pence: int) -> str:
    return f"{abs(pence) / 100:,.2f}"


def _pounds(pence: int) -> str:
    return f"£{abs(pence) / 100:,.2f}"


class _Pdf:
    """A thin drawing layer: text at a baseline, optionally right-aligned to x."""

    def __init__(self, title: str):
        self.doc = pymupdf.open()
        self.title = title
        self.page = None

    def new_page(self):
        self.page = self.doc.new_page(width=PAGE_W, height=PAGE_H)
        return self.page

    def text(self, x: float, y: float, s: str, size: float = 8, bold: bool = False, right: bool = False) -> None:
        font = BOLD if bold else FONT
        if right:
            x -= pymupdf.get_text_length(s, fontname=font, fontsize=size)
        self.page.insert_text((x, y), s, fontsize=size, fontname=font)

    def line(self, y: float, x0: float = 40, x1: float = 555) -> None:
        self.page.draw_line((x0, y), (x1, y), color=(0.75, 0.75, 0.75), width=0.5)

    def save(self, path: Path) -> None:
        self.doc.set_metadata({"title": self.title, "author": "slopFi demo", "subject": "Fictional demo data",
                               "creator": "slopFi", "producer": "slopFi", "creationDate": FIXED_DATE,
                               "modDate": FIXED_DATE})
        path.parent.mkdir(parents=True, exist_ok=True)
        self.doc.save(path, garbage=3, deflate=True, no_new_id=True)
        self.doc.close()


def _month_bounds(y: int, m: int) -> tuple[date, date]:
    return date(y, m, 1), date(y, m, calendar.monthrange(y, m)[1])


def _in(txns: list[Txn], start: date, end: date) -> list[Txn]:
    return [t for t in txns if start <= t.day <= end]


def _totals(txns: list[Txn]) -> tuple[int, int]:
    return sum(t.pence for t in txns if t.pence > 0), -sum(t.pence for t in txns if t.pence < 0)


# ====================================================================== HSBC
# Columns (hsbc_current.Columns): date x0 < 100, type 100-135, details 135-340, amounts right-aligned to the
# header words: "Paid out" ends at 389, "Paid in" at 471, "Balance" at 550. A "D" after a balance = overdrawn.
H_DATE, H_TYPE, H_DETAIL, H_OUT, H_IN, H_BAL = 40, 105, 140, 389, 471, 550
H_ROW, H_BOTTOM = 11, 770


def _hsbc_rows(txns: list[Txn], opening: int) -> list[list[dict]]:
    """Printable rows grouped into blocks (one block per transaction, so a transaction never splits across pages)."""
    blocks: list[list[dict]] = []
    balance = opening
    for i, t in enumerate(txns):
        balance += t.pence
        first_of_day = i == 0 or txns[i - 1].day != t.day
        last_of_day = i == len(txns) - 1 or txns[i + 1].day != t.day
        rows = []
        for j, line in enumerate(t.lines):
            row = {"date": t.day.strftime("%d %b %y") if first_of_day and j == 0 else "",
                   "type": t.code if j == 0 else "", "detail": line, "out": "", "in": "", "bal": "", "od": False}
            if j == len(t.lines) - 1:
                row["out" if t.pence < 0 else "in"] = _money(t.pence)
                if last_of_day:
                    row["bal"], row["od"] = _money(balance), balance < 0
            rows.append(row)
        blocks.append(rows)
    return blocks


def _hsbc_header(pdf: _Pdf, y: float) -> None:
    pdf.text(H_DATE, y, "Date", bold=True)
    pdf.text(H_TYPE, y, "Payment type and details", bold=True)
    pdf.text(H_OUT, y, "Paid out", bold=True, right=True)
    pdf.text(H_IN, y, "Paid in", bold=True, right=True)
    pdf.text(H_BAL, y, "Balance", bold=True, right=True)
    pdf.line(y + 4)


def _hsbc_balance_row(pdf: _Pdf, y: float, label: str, balance: int, day: str = "") -> None:
    if day:
        pdf.text(H_DATE, y, day)
    pdf.text(H_DETAIL, y, label, bold=True)
    pdf.text(H_BAL, y, _money(balance), right=True)
    if balance < 0:
        pdf.text(H_BAL + 3, y, "D")


def write_hsbc(acct: Account, y: int, m: int, path: Path) -> Path:
    start, end = _month_bounds(y, m)
    txns = _in(acct.txns, start, end)
    opening = acct.balance_on(start - timedelta(days=1))
    paid_in, paid_out = _totals(txns)
    closing = opening + paid_in - paid_out

    pdf = _Pdf(f"Demo current account statement {start:%B %Y}")
    pdf.new_page()
    pdf.text(40, 30, DISCLAIMER, size=7)
    pdf.text(40, 58, "HSBC UK", size=16, bold=True)
    pdf.text(555, 58, "www.hsbc.co.uk", size=8, right=True)
    pdf.text(40, 86, "Your Statement", size=12, bold=True)
    pdf.text(40, 100, "Bank Account")
    pdf.text(40, 112, f"{start.day} {start:%B} to {end.day} {end:%B %Y}")
    for k, line in enumerate([acct.holder, *[a.upper() for a in ADDRESS]]):
        pdf.text(40, 140 + 11 * k, line)
    pdf.text(40, 204, "Account Summary", size=9, bold=True)
    for k, (label, value) in enumerate((("Opening Balance", opening), ("Payments In", paid_in),
                                        ("Payments Out", paid_out), ("Closing Balance", closing))):
        yy = 218 + 12 * k
        pdf.text(40, yy, label)
        pdf.text(300, yy, _pounds(value), right=True)
        if value < 0:
            pdf.text(306, yy, "D")          # far enough from the amount to be its own word, as the parser expects
    pdf.text(40, 285, "Account Name", bold=True)
    pdf.text(350, 285, "Sortcode", bold=True)
    pdf.text(450, 285, "Account Number", bold=True)
    pdf.text(40, 297, acct.holder)
    pdf.text(350, 297, acct.sort_code)
    pdf.text(450, 297, acct.number)

    _hsbc_header(pdf, 330)
    pdf.text(H_DATE, 345, start.strftime("%d %b %y"))
    pdf.text(H_DETAIL, 345, "BALANCE BROUGHT FORWARD", bold=True)
    pdf.text(H_BAL, 345, _money(opening), right=True)
    if opening < 0:
        pdf.text(H_BAL + 3, 345, "D")
    yy = 345 + H_ROW
    balance = opening
    blocks = _hsbc_rows(txns, opening)
    for b, (block, t) in enumerate(zip(blocks, txns)):
        if yy + H_ROW * len(block) > H_BOTTOM:
            _hsbc_balance_row(pdf, yy, "BALANCE CARRIED FORWARD", balance)
            pdf.text(40, 815, DISCLAIMER, size=7)
            pdf.new_page()
            _hsbc_header(pdf, 70)
            _hsbc_balance_row(pdf, 85, "BALANCE BROUGHT FORWARD", balance)
            yy = 85 + H_ROW
        for row in block:
            if row["date"]:
                pdf.text(H_DATE, yy, row["date"])
            if row["type"]:
                pdf.text(H_TYPE, yy, row["type"])
            pdf.text(H_DETAIL, yy, row["detail"])
            if row["out"]:
                pdf.text(H_OUT, yy, row["out"], right=True)
            if row["in"]:
                pdf.text(H_IN, yy, row["in"], right=True)
            if row["bal"]:
                pdf.text(H_BAL, yy, row["bal"], right=True)
                if row["od"]:
                    pdf.text(H_BAL + 3, yy, "D")
            yy += H_ROW
        balance += t.pence
    _hsbc_balance_row(pdf, yy, "BALANCE CARRIED FORWARD", closing)
    pdf.text(40, 815, DISCLAIMER, size=7)
    pdf.save(path)
    return path


# ====================================================================== Amex
# Columns (amex_card): transaction date x0 < 30 ("Jun 17"), process date ~58, details from 101, foreign amount
# right-aligned at 417 on its own row, sterling amount right-aligned at 533, "CR" under the amount for a credit.
A_DATE, A_PROC, A_DETAIL, A_FOREIGN, A_AMOUNT = 20, 58, 101, 417, 533
A_ROW, A_BOTTOM = 11, 770


def _amex_block(t: Txn) -> list[list[tuple[float, str, bool]]]:
    """Rows for one transaction: [(x, text, right_aligned), ...] per row."""
    proc = t.day + timedelta(days=1)
    rows = [[(A_DATE, t.day.strftime("%b"), False), (A_DATE + 18, str(t.day.day), False),
             (A_PROC, proc.strftime("%b"), False), (A_PROC + 18, str(proc.day), False),
             (A_DETAIL, t.lines[0], False), (A_AMOUNT, _money(t.pence), True)]]
    for line in t.lines[1:]:
        rows.append([(A_DETAIL, line, False)])
    if t.fx:
        currency, foreign, rate = t.fx
        rows.append([(A_FOREIGN, _money(foreign), True)])
        rows.append([(A_FOREIGN, currency, True)])
        rows.append([(A_DETAIL, f"Exchange Rate {rate} + Nonsterling Transaction Fee {_money(t.fee_pence)}", False)])
    if t.pence > 0:
        rows.append([(A_AMOUNT, "CR", True)])
    return rows


def _amex_header(pdf: _Pdf, y: float) -> None:
    pdf.text(A_DATE, y, "Date", bold=True)
    pdf.text(A_PROC, y, "Processed", bold=True)
    pdf.text(A_DETAIL, y, "Transaction Details", bold=True)
    pdf.text(A_FOREIGN, y, "Foreign Spend", bold=True, right=True)
    pdf.text(A_AMOUNT, y, "Amount £", bold=True, right=True)
    pdf.line(y + 4, 20, 540)


def write_amex(acct: Account, y: int, m: int, path: Path) -> Path:
    start, end = _month_bounds(y, m)
    txns = _in(acct.txns, start, end)
    prev = -acct.balance_on(start - timedelta(days=1))          # owed, positive
    credits, debits = _totals(txns)
    closing = prev - credits + debits

    def owed(v: int) -> list[str]:
        return [_pounds(v), "CR"] if v < 0 else [_pounds(v)]

    pdf = _Pdf(f"Demo credit card statement {start:%B %Y}")
    pdf.new_page()
    pdf.text(20, 30, DISCLAIMER, size=7)
    pdf.text(20, 58, "American Express", size=16, bold=True)
    pdf.text(555, 58, "www.americanexpress.co.uk", right=True)
    pdf.text(20, 84, "Statement of Account", size=12, bold=True)
    pdf.text(20, 104, "Prepared for", bold=True)
    pdf.text(20, 116, acct.holder)
    pdf.text(20, 140, "Membership Number", bold=True)
    pdf.text(20, 152, acct.number)
    pdf.text(20, 176, f"From {start.day} {start:%B} to {end.day} {end:%B %Y}")
    labels = [(20, "Previous Closing Balance"), (160, "Payments & Credits"), (300, "New Spend"), (420, "Closing Balance")]
    for x, label in labels:
        pdf.text(x, 204, label, bold=True)
    values = [(20, owed(prev)), (160, [_pounds(credits)]), (300, [_pounds(debits)]), (420, owed(closing))]
    for k, (x, tokens) in enumerate(values):
        pdf.text(x, 217, " ".join(tokens))
        if k < 3:
            pdf.text(values[k + 1][0] - 12, 217, ["-", "+", "="][k])
    pdf.text(20, 236, "Please pay the closing balance by the due date to avoid interest.", size=7)

    _amex_header(pdf, 270)
    yy = 284
    for t in txns:
        block = _amex_block(t)
        if yy + A_ROW * len(block) > A_BOTTOM:
            pdf.text(20, 790, "How you can pay: by Direct Debit from your bank account.", size=7)
            pdf.text(20, 815, DISCLAIMER, size=7)
            pdf.new_page()
            _amex_header(pdf, 60)
            yy = 74
        for row in block:
            for x, s, right in row:
                pdf.text(x, yy, s, right=right)
            yy += A_ROW
    pdf.line(yy - 6, 20, 540)
    pdf.text(A_DETAIL - 81, yy + 4, f"Total new spend {_pounds(debits)}", bold=True)
    pdf.text(20, 815, DISCLAIMER, size=7)
    pdf.save(path)
    return path


# ===================================================================== Monzo
# monzo_pdf: header values sit on the row above their label at x > 300; rows are newest first with the date at
# x < 100, description 140-370 (wrapped lines 8pt above or below the dated row), amount 370-455, balance > 455.
M_DATE, M_DESC, M_AMOUNT, M_BAL = 40, 145, 445, 540
M_LINE, M_GAP, M_BOTTOM, M_DESC_WIDTH, M_SIZE = 8, 24, 780, 215, 7


def _wrap(pieces: list[str], width: float = M_DESC_WIDTH, size: float = M_SIZE, limit: int | None = 3) -> list[str]:
    """Word-wrap each piece to the column width; each piece starts on a new line."""
    out: list[str] = []
    for piece in pieces:
        current = ""
        for word in piece.split():
            trial = f"{current} {word}".strip()
            if current and pymupdf.get_text_length(trial, fontname=FONT, fontsize=size) > width:
                out.append(current)
                current = word
            else:
                current = trial
        if current:
            out.append(current)
    return out[:limit] if limit else out


def _signed(pence: int) -> str:
    return f"{'-' if pence < 0 else ''}{_money(pence)}"


def _monzo_section(pdf: _Pdf, hh: Household, title: str, labels: list[tuple[str, str]], txns: list[Txn],
                   opening: int, acct: Account) -> None:
    pdf.new_page()
    pdf.text(40, 36, DISCLAIMER, size=7)
    pdf.text(40, 64, "Monzo", size=16, bold=True)
    pdf.text(40, 92, title, size=12, bold=True)
    pdf.text(40, 108, f"{hh.start:%d/%m/%Y} - {hh.end:%d/%m/%Y}", size=9)
    for k, line in enumerate([acct.holder, *ADDRESS]):
        pdf.text(40, 132 + 12 * k, line)
    pdf.text(40, 196, f"Sort code: {acct.sort_code}")
    pdf.text(40, 208, f"Account number: {acct.number}")
    for k, (value, label) in enumerate(labels):
        top = 132 + 30 * k
        pdf.text(360, top, value, size=10, bold=True)
        pdf.text(360, top + 11, label, size=8)
    table_y = max(232, 132 + 30 * len(labels) + 6)
    _monzo_table_header(pdf, table_y)

    # running balances, then print newest first
    balance, rows = opening, []
    for t in txns:
        balance += t.pence
        rows.append((t, balance))
    yy = table_y + 18
    for t, bal in reversed(rows):
        lines = _wrap(t.lines)
        height = M_LINE * (len(lines) - 1)
        if yy + height > M_BOTTOM:
            pdf.text(40, 815, DISCLAIMER, size=7)
            pdf.new_page()
            _monzo_table_header(pdf, 60)
            yy = 78
        pdf.text(M_DATE, yy, t.day.strftime("%d/%m/%Y"), size=M_SIZE)
        pdf.text(M_AMOUNT, yy, _signed(t.pence), size=M_SIZE, right=True)
        pdf.text(M_BAL, yy, _signed(bal), size=M_SIZE, right=True)
        for k, line in enumerate(lines):
            pdf.text(M_DESC, yy + M_LINE * k, line, size=M_SIZE)
        yy += height + M_GAP
    pdf.text(40, 815, DISCLAIMER, size=7)


def _monzo_table_header(pdf: _Pdf, y: float) -> None:
    pdf.text(M_DATE, y, "Date", bold=True)
    pdf.text(M_DESC, y, "Description", bold=True)
    pdf.text(M_AMOUNT, y, "(GBP) Amount", bold=True, right=True)
    pdf.text(M_BAL, y, "(GBP) Balance", bold=True, right=True)
    pdf.line(y + 4)


def _pot_closing(pot: Pot) -> int:
    return pot.opening + sum(t.pence for t in pot.txns)


def write_monzo_pdf(acct: Account, hh: Household, path: Path) -> Path:
    txns = _in(acct.txns, hh.start, hh.end)
    closing = acct.opening + sum(t.pence for t in txns)
    total = closing + sum(_pot_closing(p) for p in acct.pots)
    paid_in, paid_out = _totals(txns)
    pdf = _Pdf(f"Demo current account statement {hh.start:%b %Y} to {hh.end:%b %Y}")
    _monzo_section(pdf, hh, "Personal Account statement", [
        (f"£{total / 100:,.2f}", "Total balance"),
        (f"£{closing / 100:,.2f}" if closing >= 0 else f"-£{-closing / 100:,.2f}", "Personal Account balance"),
        (f"-£{paid_out / 100:,.2f}", "Total outgoings"),
        (f"+£{paid_in / 100:,.2f}", "Total deposits"),
    ], txns, acct.opening, acct)
    for pot in acct.pots:
        p_in, p_out = _totals(pot.txns)
        _monzo_section(pdf, hh, "Pot statement", [
            (f"£{_pot_closing(pot) / 100:,.2f}", "Pot balance"),
            (f"-£{p_out / 100:,.2f}", "Total outgoings"),
            (f"+£{p_in / 100:,.2f}", "Total deposits"),
            (pot.name, "Pot name"),
            (pot.pot_type, "Pot type"),
        ], pot.txns, pot.opening, acct)
    pdf.new_page()
    pdf.text(40, 60, "Important information about compensation arrangements", size=11, bold=True)
    for k, line in enumerate([
        "This page stands in for the deposit protection notice a real statement would carry.",
        "The account, the pots and the people on this statement are fictional.",
    ]):
        pdf.text(40, 84 + 12 * k, line)
    pdf.text(40, 815, DISCLAIMER, size=7)
    pdf.save(path)
    return path


# ================================================================ Monzo CSV
CSV_COLUMNS = ["Transaction ID", "Date", "Time", "Type", "Name", "Emoji", "Category", "Amount", "Currency",
               "Local amount", "Local currency", "Notes and #tags", "Address", "Receipt", "Description",
               "Category split", "Money Out", "Money In"]


def write_monzo_csv(acct: Account, hh: Household, path: Path) -> Path:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(CSV_COLUMNS)
    for i, t in enumerate(_in(acct.txns, hh.start, hh.end)):
        amount = f"{t.pence / 100:.2f}"
        local, local_ccy = amount, "GBP"
        if t.fx:
            local, local_ccy = f"{-t.fx[1] / 100 if t.pence < 0 else t.fx[1] / 100:.2f}", t.fx[0]
        w.writerow([
            f"tx_demo{hh.seed:04d}{i:05d}", t.day.strftime("%d/%m/%Y"),
            f"{8 + (i * 7) % 13:02d}:{(i * 13) % 60:02d}:{(i * 29) % 60:02d}", t.code, t.lines[0], "", t.category,
            amount, "GBP", local, local_ccy, "", "", "", t.lines[1] if len(t.lines) > 1 else t.lines[0].upper(), "",
            amount if t.pence < 0 else "", amount if t.pence > 0 else "",
        ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(buf.getvalue(), encoding="utf-8")
    return path


# ===================================================================== all
# ================================================================== Barclays
# barclays_current: date x0 < 92 ("02 Mar", no year, first row of each day only), description from 109 (92 for the
# "Start balance" / "End balance" rows) wrapped at ~140pt, amounts right-aligned under the header words:
# "Money out" ends at 305, "Money in" at 361, "Balance" at 414. The amount sits on the transaction's first row;
# the balance is printed once per day, on the first row of the day's last transaction. The type is not a column:
# it is the printed prefix ("Card Payment to", "Direct Debit to", ...), so Txn.code is the parser's code and the
# writer prints the prefix for it. A card payment's purchase date ("On 28 Feb") runs on from the payee; "Ref: ..."
# and "Timed at ..." lines start their own line. Overdrawn balances are printed with a leading minus (assumed:
# the reference statement never goes overdrawn).
B_DATE, B_DESC, B_DESC_BAL, B_OUT, B_IN, B_BAL = 58, 109, 92, 306, 359, 413
B_ROW, B_BOTTOM, B_DESC_WIDTH, B_SIZE = 11, 745, 140, 8
B_PREFIX = {"DD": "Direct Debit to", "CARD": "Card Payment to", "CR": "Received From", "BP": "Bill Payment to",
            "ATM": "Cash Machine Withdrawal at", "SO": "Standing Order to", "TFR": "Transfer to", "FP": "Payment to"}


def _signed_money(pence: int) -> str:
    return f"-{_money(pence)}" if pence < 0 else _money(pence)


def _barclays_lines(t: Txn) -> list[str]:
    """The printed rows of one transaction's description: prefix + payee (+ the inline "On dd Mon"), wrapped,
    then each further line (Ref:, Timed at, ...) wrapped on its own."""
    prefix = B_PREFIX.get(t.code, t.code)
    head = f"{prefix} {t.lines[0]}".strip()
    pieces: list[str] = []
    on = next((line for line in t.lines[1:] if line.startswith("On ")), "")
    if t.fx:
        # the parser's "EUR 3.50 @ 1.16" and fee lines are printed as Barclays' one long sentence
        currency, foreign, rate = t.fx
        head = f"{head} {currency} {_money(foreign)} {on} at VISA Exchange Rate {rate}"
        if t.fee_pence:
            head += f" The Final GBP Amount Includes A Non-Sterling Transaction Fee of £ {_money(t.fee_pence)}"
    for line in t.lines[1:]:
        if line.startswith("On ") and not pieces:
            if not t.fx:
                head = f"{head} {line}"
        elif t.fx and (" @ " in line or line.startswith("Non-Sterling")):
            continue
        else:
            pieces.append(line)
    return _wrap([head, *pieces], width=B_DESC_WIDTH, size=B_SIZE, limit=None)


def _barclays_header(pdf: _Pdf, y: float) -> None:
    pdf.text(B_DATE, y, "Date", bold=True, size=B_SIZE)
    pdf.text(B_DESC_BAL, y, "Description", bold=True, size=B_SIZE)
    pdf.text(B_OUT - 1, y, "Money out", bold=True, right=True, size=B_SIZE)
    pdf.text(B_IN + 2, y, "Money in", bold=True, right=True, size=B_SIZE)
    pdf.text(B_BAL + 1, y, "Balance", bold=True, right=True, size=B_SIZE)
    pdf.line(y + 4, 55, 420)


def _barclays_page_top(pdf: _Pdf, acct: Account, page_no: int) -> float:
    """A continuation page: the account line, the section title and the table header. Returns the first row y."""
    pdf.text(59, 23, f"Sort code {acct.sort_code} \u2022 Account number {acct.number}", size=B_SIZE)
    pdf.text(61, 45, "Your transactions", size=12, bold=True)
    _barclays_header(pdf, 66)
    return 83


def _barclays_footer(pdf: _Pdf, page_no: int, continued: bool) -> None:
    if continued:
        pdf.text(409, 755, "Continued", size=B_SIZE, right=True)
    pdf.text(57, 800, "Demo Bank UK PLC. Not authorised by anyone: this is fictional demo data.", size=7)
    pdf.text(57, 815, DISCLAIMER, size=7)
    pdf.text(571, 808, f"Page {page_no}", size=B_SIZE, right=True)


def write_barclays(acct: Account, y: int, m: int, path: Path, period: tuple[date, date] | None = None) -> Path:
    """One Barclays-style statement for a calendar month, or for `period` (start, end) when given: a Barclays
    statement runs from the day after the previous one to the statement date, which can straddle a year end."""
    start, end = period or _month_bounds(y, m)
    txns = _in(acct.txns, start, end)
    opening = acct.balance_on(start - timedelta(days=1))
    money_in, money_out = _totals(txns)
    closing = opening + money_in - money_out

    def dm(d: date) -> str:
        return f"{d.day:02d} {d:%b}"

    pdf = _Pdf(f"Demo current account statement {start:%B %Y}")
    pdf.new_page()
    pdf.text(40, 12, DISCLAIMER, size=7)
    pdf.text(295, 23, f"Statement date {dm(end)} {end.year}", size=B_SIZE)
    pdf.text(295, 35, f"Last statement {dm(start - timedelta(days=1))} {(start - timedelta(days=1)).year}", size=B_SIZE)
    pdf.text(434, 23, "Barclays Bank", size=13, bold=True)
    pdf.text(434, 41, "Account", size=13, bold=True)
    pdf.text(434, 73, f"{dm(start)} - {dm(end)} {end.year}", size=B_SIZE)
    pdf.text(434, 90, acct.holder, size=B_SIZE)
    for k, line in enumerate([f"Sort Code {acct.sort_code}", f"Account no. {acct.number}", "SWIFTBIC DEMOGB00",
                              f"IBAN GB00 DEMO {acct.sort_code.replace('-', '')} {acct.number}"]):
        pdf.text(434, 106 + 10 * k, "\u2022", size=B_SIZE)
        pdf.text(441, 106 + 10 * k, line, size=B_SIZE)
    for k, line in enumerate([acct.holder.upper(), *[a.upper() for a in ADDRESS]]):
        pdf.text(71, 151 + 9 * k, line, size=B_SIZE)
    pdf.text(438, 158, "At a glance", size=10, bold=True)
    for k, (label, value) in enumerate((("Start balance", opening), ("Money in", money_in), ("Money out", money_out),
                                        ("End balance", closing))):
        yy = 177 + 15 * k
        pdf.text(438, yy, label, size=B_SIZE)
        pdf.text(561, yy, ("-" if value < 0 else "") + _pounds(value), size=B_SIZE, right=True)
    pdf.text(57, 257, "Your Barclays Bank Account statement", size=15, bold=True)
    pdf.text(57, 291, "Current account statement", size=10)
    pdf.text(434, 263, "Your deposit is eligible for protection by the", size=7)
    pdf.text(434, 273, "Financial Services Compensation Scheme.", size=7)
    pdf.text(61, 335, "Your transactions", size=12, bold=True)
    pdf.text(74, 358, "Bank Giro    Cash machine    Contactless    Debit Card    Direct Debit    Online", size=7)
    _barclays_header(pdf, 391)
    pdf.text(B_DATE, 408, dm(start), size=B_SIZE)
    pdf.text(B_DESC_BAL, 408, "Start balance", size=B_SIZE)
    pdf.text(B_BAL, 408, _signed_money(opening), size=B_SIZE, right=True)

    yy = 428
    page_no = 1
    balance = opening
    for i, t in enumerate(txns):
        lines = _barclays_lines(t)
        if yy + B_ROW * len(lines) > B_BOTTOM:
            _barclays_footer(pdf, page_no, continued=True)
            pdf.new_page()
            page_no += 1
            yy = _barclays_page_top(pdf, acct, page_no)
        balance += t.pence
        first_of_day = i == 0 or txns[i - 1].day != t.day
        last_of_day = i == len(txns) - 1 or txns[i + 1].day != t.day
        if first_of_day:
            pdf.text(B_DATE, yy, dm(t.day), size=B_SIZE)
        for j, line in enumerate(lines):
            pdf.text(B_DESC, yy, line, size=B_SIZE)
            if j == 0:
                pdf.text(B_OUT if t.pence < 0 else B_IN, yy, _money(t.pence), size=B_SIZE, right=True)
                if last_of_day:
                    pdf.text(B_BAL, yy, _signed_money(balance), size=B_SIZE, right=True)
            yy += B_ROW
        yy += 7  # the gap Barclays leaves between transactions
    if yy + B_ROW > B_BOTTOM:
        _barclays_footer(pdf, page_no, continued=True)
        pdf.new_page()
        page_no += 1
        yy = _barclays_page_top(pdf, acct, page_no)
    pdf.text(B_DATE, yy, dm(end), size=B_SIZE)
    pdf.text(B_DESC_BAL, yy, "End balance", size=B_SIZE)
    pdf.text(B_BAL, yy, _signed_money(closing), size=B_SIZE, right=True)
    pdf.text(57, yy + 30, "Anything Wrong? If you've spotted any incorrect or unusual transactions, get in touch.", size=7)
    pdf.text(57, yy + 60, "This account does not pay credit interest", size=B_SIZE)
    _barclays_footer(pdf, page_no, continued=False)
    pdf.new_page()
    page_no += 1
    pdf.text(57, 60, "Important information about compensation arrangements", size=12, bold=True)
    pdf.text(57, 80, "Fictional information page: a real statement carries several pages of terms here.", size=B_SIZE)
    _barclays_footer(pdf, page_no, continued=False)
    pdf.save(path)
    return path


def write_all(hh: Household, root: Path) -> list[Path]:
    """Every statement file under root/<person>/<account>/. Returns the paths written, in a stable order."""
    out: list[Path] = []
    for acct in hh.accounts.values():
        folder = root / acct.folder
        if acct.fmt == "hsbc_pdf":
            for y, m in hh.months:
                out.append(write_hsbc(acct, y, m, folder / f"hsbc-joint-{y}-{m:02d}.pdf"))
        elif acct.fmt == "amex_pdf":
            for y, m in hh.months:
                out.append(write_amex(acct, y, m, folder / f"amex-{acct.owner}-{y}-{m:02d}.pdf"))
        elif acct.fmt == "barclays_pdf":
            for y, m in hh.months:
                out.append(write_barclays(acct, y, m, folder / f"barclays-{acct.owner}-{y}-{m:02d}.pdf"))
        elif acct.fmt == "monzo_pdf":
            out.append(write_monzo_pdf(acct, hh, folder / f"monzo-{acct.owner}-{hh.start:%Y-%m}-to-{hh.end:%Y-%m}.pdf"))
        elif acct.fmt == "monzo_csv":
            out.append(write_monzo_csv(acct, hh, folder / f"monzo-{acct.owner}-export-{hh.end:%Y-%m}.csv"))
    return out
